SELECT 
    RESTAURANT_INFO.NAME AS RESTAURANT_NAME,
    MENUITEMS.NAME AS MENUITEMS_NAME
FROM 
    RESTAURANT_INFO
LEFT JOIN 
    MENUITEMS
ON 
    RESTAURANT_INFO.RESTAURANT_ID = MENUITEMS.RESTAURANT_ID;


SELECT 
    RESTAURANT_INFO.NAME, 
    RESTAURANT_INFO.CONTACT_NUMBER,
    COALESCE(MENUITEMS.NAME, 'NO MENU ITEMS') AS MENU_ITEM_NAME,
    MENUITEMS.AVAILABILITY
FROM 
    RESTAURANT_INFO
LEFT JOIN 
    MENUITEMS
ON 
    RESTAURANT_INFO.RESTAURANT_ID = MENUITEMS.RESTAURANT_ID;
